name: Build Layer ZIP

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Read version
        id: package_lock_json
        run: |
          content=$(cat ./package-lock.json)
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=packageLockJson::$content"
      - name: Variables
        id: vars
        run: |
          sharp_version="${{ fromJSON(steps.package_lock_json.outputs.packageLockJson).dependencies.sharp.version }}"
          echo "::set-output name=sharp_version::$sharp_version"

          release_exists="true"
          git show-ref --tags --quiet --verify -- "refs/tags/$sharp_version" || release_exists="false"
          echo "::set-output name=release_exists::$release_exists"
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: amazon-linux-sharp-layer:dev
      - name: Copy artifacts
        run: docker run -v "${{ github.workspace }}/dist":/dist amazon-linux-sharp-layer:dev
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sharp-lambda-layer.zip
          path: dist/sharp-layer.zip
          if-no-files-found: error
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.vars.outputs.sharp_version }}
          files: dist/sharp-layer.zip
